const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#1a1a1a',
  },
  header: {
    padding: '16px',
    borderBottom: '1px solid #444',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    color: '#fff',
    fontSize: '16px',
    margin: 0,
    fontWeight: '600',
  },
  controls: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  modelSelect: {
    padding: '6px 10px',
    backgroundColor: '#2a2a2a',
    color: '#fff',
    border: '1px solid #444',
    borderRadius: '4px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  tempControl: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  tempLabel: {
    color: '#aaa',
    fontSize: '12px',
    cursor: 'help',
  },
  tempSlider: {
    width: '80px',
  },
  clearButton: {
    padding: '6px 10px',
    backgroundColor: '#2a2a2a',
    color: '#fff',
    border: '1px solid #444',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  messagesContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  emptyState: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#666',
  },
  emptyText: {
    fontSize: '16px',
  },
  message: {
    padding: '12px',
    borderRadius: '8px',
    maxWidth: '80%',
  },
  userMessage: {
    backgroundColor: '#3b82f6',
    color: '#fff',
    alignSelf: 'flex-end',
    marginLeft: 'auto',
  },
  aiMessage: {
    backgroundColor: '#2a2a2a',
    color: '#fff',
    alignSelf: 'flex-start',
    border: '1px solid #444',
  },
  summaryMessage: {
    backgroundColor: '#7c3aed',
    color: '#fff',
    alignSelf: 'flex-start',
    border: '1px solid #6d28d9',
    maxWidth: '90%',
  },
  systemMessage: {
    backgroundColor: '#10b981',
    color: '#fff',
    alignSelf: 'center',
    fontSize: '13px',
    maxWidth: '90%',
  },
  messageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
    fontSize: '12px',
    opacity: 0.8,
  },
  messageRole: {
    fontWeight: '600',
  },
  messageTime: {
    fontSize: '11px',
  },
  messageContent: {
    fontSize: '14px',
    lineHeight: '1.5',
    whiteSpace: 'pre-wrap',
  },
  generatingIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px',
    backgroundColor: '#2a2a2a',
    borderRadius: '8px',
    alignSelf: 'flex-start',
    border: '1px solid #444',
  },
  summaryIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px',
    backgroundColor: '#7c3aed',
    borderRadius: '8px',
    alignSelf: 'center',
    border: '1px solid #6d28d9',
  },
  buildingIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px',
    backgroundColor: '#3b82f6',
    borderRadius: '8px',
    alignSelf: 'center',
    border: '1px solid #2563eb',
  },
  dots: {
    display: 'flex',
    gap: '4px',
    color: '#3b82f6',
  },
  spinner: {
    fontSize: '20px',
  },
  generatingText: {
    color: '#aaa',
    fontSize: '13px',
  },
  summaryText: {
    color: '#fff',
    fontSize: '13px',
    fontWeight: '500',
  },
  buildingText: {
    color: '#fff',
    fontSize: '13px',
    fontWeight: '500',
  },
  actionButtons: {
    padding: '12px 16px',
    borderTop: '1px solid #444',
    borderBottom: '1px solid #444',
    display: 'flex',
    gap: '12px',
  },
  summaryButton: {
    flex: 1,
    padding: '14px 20px',
    backgroundColor: '#7c3aed',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  buildButton: {
    flex: 1,
    padding: '14px 20px',
    backgroundColor: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  buttonDisabled: {
    backgroundColor: '#374151',
    cursor: 'not-allowed',
    opacity: 0.5,
  },
  inputForm: {
    padding: '16px',
    display: 'flex',
    gap: '12px',
  },
  input: {
    flex: 1,
    padding: '10px 12px',
    backgroundColor: '#2a2a2a',
    color: '#fff',
    border: '1px solid #444',
    borderRadius: '4px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'none',
  },
  sendButton: {
    padding: '10px 24px',
    backgroundColor: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  sendButtonDisabled: {
    backgroundColor: '#374151',
    cursor: 'not-allowed',
    opacity: 0.5,
  },
};

export default styles;
