const styles = {
  app: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    backgroundColor: '#0a0a0a',
    color: '#fff',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    height: '60px',
    backgroundColor: '#1a1a1a',
    borderBottom: '1px solid #333',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 20px',
    gap: '20px',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    flex: 1,
  },
  logo: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '600',
    whiteSpace: 'nowrap',
  },
  projectSelector: {
    minWidth: '300px',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  saveIndicator: {
    fontSize: '13px',
    fontWeight: '500',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
  },
  sidebar: {
    width: '250px',
    backgroundColor: '#1a1a1a',
    borderRight: '1px solid #333',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  nav: {
    padding: '20px',
    borderBottom: '1px solid #333',
  },
  navTitle: {
    margin: '0 0 12px 0',
    fontSize: '13px',
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  navButton: {
    width: '100%',
    padding: '12px 16px',
    backgroundColor: 'transparent',
    color: '#aaa',
    border: 'none',
    borderRadius: '6px',
    textAlign: 'left',
    cursor: 'pointer',
    marginBottom: '4px',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    transition: 'all 0.2s',
  },
  navButtonActive: {
    backgroundColor: '#3b82f6',
    color: '#fff',
  },
  navIcon: {
    fontSize: '18px',
  },
  navToggle: {
    background: 'transparent',
    border: 'none',
    color: '#aaa',
    cursor: 'pointer',
    padding: '6px',
    borderRadius: '4px',
  },
  projectInfo: {
    padding: '20px',
    flex: 1,
    overflow: 'auto',
  },
  projectInfoTitle: {
    margin: '0 0 8px 0',
    fontSize: '16px',
    color: '#fff',
  },
  projectGenre: {
    display: 'inline-block',
    padding: '4px 8px',
    backgroundColor: '#3b82f6',
    color: '#fff',
    borderRadius: '4px',
    fontSize: '11px',
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: '12px',
  },
  projectDescription: {
    margin: 0,
    fontSize: '13px',
    color: '#aaa',
    lineHeight: '1.5',
  },
  centerPanel: {
    flex: 1,
    overflow: 'hidden',
  },
  // sidebarCollapseButton removed
  welcome: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
  },
  welcomeContent: {
    maxWidth: '600px',
    textAlign: 'center',
  },
  welcomeTitle: {
    fontSize: '32px',
    marginBottom: '16px',
    color: '#fff',
  },
  welcomeText: {
    fontSize: '16px',
    color: '#aaa',
    marginBottom: '40px',
    lineHeight: '1.6',
  },
  welcomeSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    textAlign: 'left',
  },
  welcomeStep: {
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
  },
  welcomeStepNumber: {
    width: '32px',
    height: '32px',
    backgroundColor: '#3b82f6',
    color: '#fff',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    fontWeight: '600',
    flexShrink: 0,
  },
  welcomeStepText: {
    margin: 0,
    color: '#ccc',
    fontSize: '14px',
    lineHeight: '1.6',
    paddingTop: '4px',
  },
  placeholder: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
  },
  placeholderTitle: {
    fontSize: '24px',
    color: '#fff',
    marginBottom: '12px',
  },
  placeholderText: {
    fontSize: '14px',
    color: '#666',
  },
};

export default styles;