const styles = {
  container: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    background: '#0a0a0a',
  },
  tabs: {
    display: 'flex',
    gap: '4px',
    padding: '16px',
    borderBottom: '1px solid #333',
    overflowX: 'auto',
    background: '#1a1a1a',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    background: 'transparent',
    border: 'none',
    borderRadius: '6px',
    color: '#888',
    fontSize: '14px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s',
  },
  tabActive: {
    background: '#3b82f6',
    color: '#fff',
  },
  tabIcon: {
    fontSize: '18px',
  },
  sidebar: {
    width: '220px',
    minWidth: '180px',
    background: '#0f1724',
    borderRight: '1px solid #233240',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
  },
  sidebarHeader: {
    marginBottom: '8px',
  },
  sidebarMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 12px',
    background: 'transparent',
    color: '#cbd5e1',
    border: 'none',
    borderRadius: '6px',
    textAlign: 'left',
    cursor: 'pointer',
  },
  sidebarItemActive: {
    background: '#12243a',
    color: '#fff',
  },
  sidebarIcon: {
    width: '20px',
    textAlign: 'center',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '24px',
    minHeight: '0',
  },
  form: {
    maxWidth: '800px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  sectionTitle: {
    margin: 0,
    color: '#fff',
    fontSize: '24px',
    fontWeight: '600',
  },
  addButton: {
    padding: '10px 16px',
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    color: '#ccc',
    fontSize: '14px',
    fontWeight: '500',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    background: '#1a1a1a',
    border: '1px solid #3a3a3a',
    borderRadius: '6px',
    color: '#fff',
    fontSize: '14px',
  },
  textarea: {
    width: '100%',
    padding: '10px 12px',
    background: '#1a1a1a',
    border: '1px solid #3a3a3a',
    borderRadius: '6px',
    color: '#fff',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  card: {
    background: '#1a1a1a',
    border: '1px solid #3a3a3a',
    borderRadius: '8px',
    padding: '20px',
    marginBottom: '16px',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '1px solid #3a3a3a',
  },
  cardTitle: {
    margin: 0,
    color: '#fff',
    fontSize: '18px',
    fontWeight: '500',
  },
  removeButton: {
    padding: '6px 12px',
    background: 'transparent',
    border: '1px solid #ef4444',
    borderRadius: '4px',
    color: '#ef4444',
    fontSize: '12px',
    cursor: 'pointer',
  },
  saveBar: {
    marginTop: '32px',
    paddingTop: '20px',
    borderTop: '1px solid #3a3a3a',
  },
  saveMessage: {
    marginLeft: '12px',
    display: 'inline-block',
    padding: '8px 12px',
    borderRadius: '6px',
    background: '#052e16',
    color: '#bbf7d0',
    border: '1px solid #064e2c',
    fontSize: '13px',
  },
  saveError: {
    marginLeft: '12px',
    display: 'inline-block',
    padding: '8px 12px',
    borderRadius: '6px',
    background: '#2b0212',
    color: '#fecaca',
    border: '1px solid #5b0211',
    fontSize: '13px',
  },
  saveButton: {
    padding: '12px 24px',
    background: '#10b981',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  loading: {
    padding: '40px',
    textAlign: 'center',
    color: '#888',
  },
  itemList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  listDetail: {
    display: 'flex',
    gap: '20px',
    alignItems: 'stretch',
  },
  listPane: {
    width: '320px',
    minWidth: '260px',
    maxHeight: '70vh',
    overflow: 'auto',
  },
  detailPane: {
    flex: 1,
    minWidth: '320px',
  },
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px',
    borderRadius: '6px',
    background: '#111',
    border: '1px solid #2a2a2a',
    cursor: 'pointer',
  },
  listItemActive: {
    background: '#172554',
    borderColor: '#3b82f6',
  },
  listItemMain: {
    flex: 1,
    paddingRight: '8px',
  },
  listItemTitle: {
    color: '#fff',
    fontSize: '14px',
    fontWeight: '600',
  },
  listItemSubtitle: {
    color: '#9ca3af',
    fontSize: '12px',
    marginTop: '4px',
  },
  listItemActions: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  smallButton: {
    padding: '6px 10px',
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
  },
  detailFullPane: {
    flex: 1,
    minWidth: '320px',
    maxWidth: '100%'
  },
  backButton: {
    padding: '8px 12px',
    background: 'transparent',
    color: '#cbd5e1',
    border: '1px solid #475569',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  empty: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#888',
  },
  emptyState: {
    padding: '40px',
    textAlign: 'center',
    color: '#888',
    background: '#1a1a1a',
    border: '1px dashed #3a3a3a',
    borderRadius: '8px',
  },
};

export default styles;
